### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by clintongreen**
Fixed typo

### CODE REVIEW

**Comment by rafaelpimpa** [comment]
Don't merge on master next time

**Comment by rfberaldo** [comment]
Thank you

**Comment by clintongreen** [comment]
Sorry, first pull request. I'll use another branch next time.

**Comment by rfberaldo** [comment]
Don't worry, I thought it was the Buefy repository, this one have only master :)

**Comment by clintongreen** [comment]
Ok cool

**Pull request merged**
